### ISSUE TITLE
Feature Request: Only mark the "default" apps while editing the uninstallation list

### ISSUE THREAD

**Issue by Giovix92** [pratyakshm/WinRice#37]
### Does your feature request involve usage of third party software?

No

### Have you written the code which adds this feature?

No

### Explain the feature

While using a different uninstallation preset, the "new" uninstallation editable-list shows up.
Instead of checking every app available in the system:
![image](https://user-images.githubusercontent.com/19226770/140663045-492bd269-a084-4136-ac12-04fdaa1e3671.png)
just mark **only** the apps already written [in the app uninstallation list](https://github.com/pratyakshm/WinRice/blob/main/doc/App-uninstallation.md#app-uninstallation). In this way, the user can only mark/not mark the other/s unwanted apps/wanted apps.

### Does this Feature Request follow the WinRice principles?

- [X] Yes

**Comment by pratyakshm** [comment]
Hi there,
Sorry I didn't respond to this issue. This sounds like a really good idea and I have tried to achieve this however I fail to do it every time. I'm not quite sure what to do with this anymore. I will try a few more times, if it works out then its really cool. Otherwise, I'm not really sure.
I'll update my status here.
Meanwhile, if any PowerShell scripter is reading this, you're more than welcome to make a PR or help me with this. I'd be glad.

**Comment by pratyakshm** [comment]
I've closed the issue as it is added to https://github.com/pratyakshm/WinRice/projects/4?add_cards_query=is%3Aopen. If you want to keep it open anyway, feel free to re-open.
